In [3]:
import numpy as np
a = np.array([-1, 0, 1])
b = np.array([2, -1, 1])
np.dot(a,b)

-1

In [4]:
a + b #ベクトル和

array([ 1, -1,  2])

In [5]:
al = [-1, 0, 1]
bl = [2, -1, 1]
al + bl

[-1, 0, 1, 2, -1, 1]

In [6]:
#cos類似度
np.dot(a,b)/(np.linalg.norm(a) * np.linalg.norm(b))

-0.2886751345948129

In [8]:
#cos類似度を返す関数
def getCos(a, b):
  return np.dot(a,b)/(np.linalg.norm(a) * np.linalg.norm(b))

In [9]:
getCos(a, b)

-0.2886751345948129

In [10]:
a1 = np.array([1, 1, 2, 0])
b1 = np.array([-1, 2, 0.5, 1])
getCos(a1,b1)

0.32659863237109044

In [12]:
A = np.array([[0,1,2],[3,4,5]])
B = np.array([[0,1],[2,3],[4,5]])
np.dot(A, B)

array([[10, 13],
       [28, 40]])

In [14]:
A = np.array([[2,3],[3,-2]])
b = np.array([-4, 7])
A_inv = np.linalg.inv(A)
A_inv

array([[ 0.15384615,  0.23076923],
       [ 0.23076923, -0.15384615]])

In [15]:
x = np.dot(A_inv, b)
x

array([ 1., -2.])

In [16]:
np.linalg.solve(A, b)

array([ 1., -2.])

In [20]:
A = np.array([[5,3],[4,9]])
eig = np.linalg.eig(A)
print(eig[0])
print(eig[1])

[ 3. 11.]
[[-0.83205029 -0.4472136 ]
 [ 0.5547002  -0.89442719]]


In [21]:
P = eig[1]
D = np.linalg.inv(P) @ A @ P
D

array([[3.00000000e+00, 1.55431223e-15],
       [0.00000000e+00, 1.10000000e+01]])

In [22]:
np.linalg.matrix_power(A,3)

array([[ 353,  489],
       [ 652, 1005]])